# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3-openjdk-11
clone:
  depth: full
pipelines:
  branches:
    ‘{master}’: # or the name of your main branch
      - step:
          name: SonarQube analysis
          caches:
            - maven
            - sonar
          script:
            - mvn verify sonar:sonar
            - sonar-scanner -Dsonar.exclusions=**/ios/**,**android/**,*.java -Dsonar.projectKey=ExcelR-Mobileapp-Flutter -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.affle.com 
definitions:
  caches:
    sonar: ~/.sonar
          
