# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.3
#image: node:16.12.0
pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - mvn sonar:sonar #npm install -g sonarqube-scanner
          - sonar-scanner -Dsonar.exclusions=**/ios/**,**android/**,*.java -Dsonar.projectKey=ExcelR-Mobileapp-Flutter -Dsonar.sources=. -Dsonar.host.url=https://sonarqube.affle.com -Dsonar.login=bd86728c044fa41117bbd0400a80f9722961e251
